name: jupyterlab-default-latest
dependencies:
  - pip
  - conda
  - nomkl
  - cytoolz
  - lz4
  - ipywidgets
  - cachey
  - streamz
  - jupyterhub-singleuser
  - jupyterlab
  - dask-labextension>=5
  - nbclassic
  - dask-gateway
  - xarray-eopf=0.1.1
  - netCDF4
  - zarr
  - fsspec
  - gdal
  - nbgitpuller
  - xarray=2024.11.0
  - folium
  - graphviz
  - mapclassify
  - matplotlib=3.10.0
  - matplotlib-inline=0.1.7
  - bottleneck=1.4.2
  - numpy=1.26.4
  - mystmd
  - cartopy
  - jupyterlab-myst
  - python-graphviz
  - geopandas
  - ipyleaflet
  - shapely
  - pystac-client
  - xcube-eopf=0.1.1
